OCR Make: build in a single prefix (no separate dir. per OCR_TYPE)
This will make it easier to build an OCR RPM and to use modules with OCR.

The major change is that everything now installs in a "standard" location
(bin/, lib/, share/) in OCR_INSTALL which now acts like a more traditional
prefix. To distinguish between OCR "flavors", OCR_TYPE is now appended
to the library built and to the ocrrun scripts. Note that include files
are installed once and are only removed with a squeaky make (an uninstall
no longer removes them because they are "shared" across OCR_TYPE). A similar
statement can be made on the scripts installed in share/ocr/scripts.

Change-Id: I4409979b6855ec00077840efd93f33408b2a22c9

diff --git a/ocr/build/x86-gasnet/ocrrun_x86-gasnet b/ocr/build/x86-gasnet/ocrrun_x86-gasnet
--- a/ocr/build/x86-gasnet/ocrrun_x86-gasnet
+++ b/ocr/build/x86-gasnet/ocrrun_x86-gasnet
@@ -2,7 +2,6 @@
 
 
 # User-provided or generated
-OCR_CONFIG=
 PROGRAM_BIN=
 
 #
@@ -35,9 +34,8 @@ fi
 
 if [ "${OCR_CONFIG}" = "" ]; then
     #Call the config generator
-    perl ${OCR_ROOT}/bin/config-generator.py
-    #TODO this only works with default CFG filename
-    OCR_CONFIG=${PWD}/default.cfg
+    python ${OCR_INSTALL}/share/ocr/scripts/Configs/config-generator.py ${PWD}/generated_ocrrun.cfg
+    OCR_CONFIG=${PWD}/generated_ocrrun.cfg
 fi
 
 # Determine what the configuration file is trying to do
@@ -46,10 +44,15 @@ fi
 # Warning: This is a very rough first implementation round
 #
 
-# Checking for MPI-backed runtime
-RES=`grep "MPI" ${OCR_CONFIG}`
+# Checking for GASNet-backed runtime
+RES=`grep "GASNet" ${OCR_CONFIG}`
 
 if [[ "$RES" != "" ]]; then
+
+    if [[ "${GASNET_CONDUIT}" == "" ]]; then
+        echo "error: The GASNET_CONDUIT env variable is not defined"
+        exit 1
+    fi
 
     if [[ "${OCR_NODEFILE}" != "" ]]; then
         # count words since hostnames shouldn't have spaces (-l only counts new lines)
@@ -61,7 +64,32 @@ if [[ "$RES" != "" ]]; then
                 echo "Warning: OCR_NUM_NODES differs from number of nodes declared in OCR_NODEFILE (${OLD_VALUE} and ${NODECOUNT})"
             fi
         fi
-        OCR_NODEFILE="-machinefile ${OCR_NODEFILE}"
+
+        if [[ "${GASNET_CONDUIT}" == "ibv" ]]; then
+            if [[ "${GASNET_IBV_SPAWNER}" == "ssh" ]]; then
+                export GASNET_SSH_NODEFILE=${OCR_NODEFILE}
+            else
+                echo "Warning: ocrrun assumes IBV/MPI spawn uses intel mpi"
+                export MPIRUN_CMD="mpirun -np %N -machinefile ${OCR_NODEFILE} %C"
+            fi
+        else
+            echo "error: ocrrun does not know how to use OCR_NODEFILE when conduit=${GASNET_CONDUIT}"
+            exit 1
+        fi
+    fi
+
+    # Try to guess the gasnet launcher
+    if [[ "${GASNET_LAUNCHER}" == "" ]]; then
+        if [[ "${GASNET_CONDUIT}" == "ibv" ]]; then
+            GASNET_LAUNCHER=gasnetrun_ibv
+        elif [[ "${GASNET_CONDUIT}" == "udp" ]]; then
+            GASNET_LAUNCHER=amudprun
+        elif [[ "${GASNET_CONDUIT}" == "mpi" ]]; then
+            GASNET_LAUNCHER=gasnetrun_mpi
+        else
+            echo "error: GASNET_LAUNCHER is not unknown for conduit=${GASNET_CONDUIT}"
+            exit 1
+        fi
     fi
 
     #If nothing has provided default to 2 instances on local node
@@ -70,19 +98,8 @@ if [[ "$RES" != "" ]]; then
         OCR_NUM_NODES=2
     fi
 
-    if [[ "${OCRRUN_GDB}" == "yes" ]]; then
-        OCR_MPI_OPTS+=" --gdb "
-    fi
+    ${GASNET_LAUNCHER} -n ${OCR_NUM_NODES} ${PROGRAM_BIN} -ocr:cfg ${OCR_CONFIG}
 
-    if [[ "${OCRRUN_VALGRIND_OPTS}" != "" ]]; then
-        OCRRUN_VALGRIND="yes";
-    fi
-
-    if [[ "${OCRRUN_VALGRIND}" == "yes" ]]; then
-        PROGRAM_BIN="valgrind ${OCRRUN_VALGRIND_OPTS} ${PROGRAM_BIN}"
-    fi
-
-    mpirun -np ${OCR_NUM_NODES} ${OCR_NODEFILE} ${OCR_MPI_OPTS} ${PROGRAM_BIN} -ocr:cfg ${OCR_CONFIG}
     RET_CODE=$?
     exit ${RET_CODE}
 fi
