Update for tg-x86 ocrrun and ocrTests
- Do not try to generate default CFG file fot tg-x86.
  It's not supported
- Updated ocrrun for tg-x86 to match the x86 one

Change-Id: I8755fa10594139332dcbbb9c5add1c78d3c349ae

diff --git a/ocr/build/tg-x86/ocrrun_tg-x86 b/ocr/build/tg-x86/ocrrun_tg-x86
--- a/ocr/build/tg-x86/ocrrun_tg-x86
+++ b/ocr/build/tg-x86/ocrrun_tg-x86
@@ -2,7 +2,6 @@
 
 
 # User-provided or generated
-OCR_CONFIG=
 PROGRAM_BIN=
 
 #
@@ -34,14 +33,25 @@ else
 fi
 
 if [ "${OCR_CONFIG}" = "" ]; then
-    #Call the config generator
-    python ${OCR_ROOT}/bin/config-generator.py
-    #TODO this only works with default CFG filename
-    OCR_CONFIG=${PWD}/default.cfg
+    echo "error: ocrrun cannot call config-generator for tg-x86 (not supported - set OCR_CONFIG)"
+    exit 1
+fi
+
+if [[ "${OCRRUN_GDB}" == "yes" ]]; then
+    PROGRAM_BIN="gdb --args ${PROGRAM_BIN}"
+fi
+
+if [[ "${OCRRUN_VALGRIND_OPTS}" != "" ]]; then
+    OCRRUN_VALGRIND="yes";
+fi
+
+if [[ "${OCRRUN_VALGRIND}" == "yes" ]]; then
+    PROGRAM_BIN="valgrind ${OCRRUN_VALGRIND_OPTS} ${PROGRAM_BIN}"
 fi
 
 # Default is regular X86-backend
 ${PROGRAM_BIN} -ocr:cfg ${OCR_CONFIG}
+
 RET_CODE=$?
 exit ${RET_CODE}
 
diff --git a/ocr/tests/ocrTests b/ocr/tests/ocrTests
--- a/ocr/tests/ocrTests
+++ b/ocr/tests/ocrTests
@@ -110,7 +110,16 @@ export OCR_TESTS_BIN_OUTPUT=
 
 if [ -z "${OCR_CONFIG}" ]; then
     export OCR_CONFIG=${OCR_INSTALL}/share/ocr/config/${OCR_TYPE}/generated_ocrTests.cfg
-    ${OCR_INSTALL}/share/ocr/scripts/Configs/config-generator.py --output ${OCR_CONFIG}
+    args="--threads 8 --alloctype mallocproxy --dbtype Lockable"
+    if [ "${OCR_TYPE}" = "x86-mpi" ]; then
+        args="${args} --guid COUNTED_MAP --target mpi"
+    elif [[ "${OCR_TYPE}" = "x86-gasnet" ]]; then
+        args="${args} --guid COUNTED_MAP --target gasnet"
+    elif [[ "${OCR_TYPE}" = "tg-x86" ]]; then
+        echo "error: ocrrun cannot call config-generator for tg-x86 (not supported - set OCR_CONFIG)"
+        exit 1
+    fi
+    ${OCR_INSTALL}/share/ocr/scripts/Configs/config-generator.py ${args} --output ${OCR_CONFIG} --remove-destination
     echo "OCR_CONFIG is not set, defaulting to ${OCR_CONFIG}"
 fi
 
