Support for GASNET as a comm-platform layer
    - [vc8] gasnet_init to happen before argument parsing to allow
            gasnet's sub-processes to access all the options.
    - [vc8] General gasnet related files cleanup
    - [vc8] Updated jenkins config to run tests with gasnet
    - [vc8] Gasnet cfg files all use lockable DB and malloc-proxy
    - [la5] Implement gasnet-comm-platform and support files
    -    amhandler       : Registry of AM handlers
    -    gasnet-message  : Manage database containing partitioned messages
    -    gasnet-am       : Interface to use gasnet-am* implementations
    -    gasnet-ammedium : Support for GASNet AM medium
    -    gasnet-amlong   : Support for GASNet AM long
    -    gasnet-comm-platform : Gasnet support for OCR
    -    gasnet-share-segment : GASNet share segment Management
    -    gasnet-message-split : Utility to split messages in several pieces
    -    gasnet-policy-domain : database of policy domains
    -    splay-tree.h         : splay and rb trees (BSD License)
         - ftp.netbsd.org/pub/NetBSD/NetBSD-current/src/sys/sys/tree.h

Change-Id: I86844529f7026f80c3dd08dac001b3e9f7fc471a

diff --git a/ocr/build/x86-pthread-gasnet/ocrrun b/ocr/build/x86-pthread-gasnet/ocrrun
--- a/ocr/build/x86-pthread-gasnet/ocrrun
+++ b/ocr/build/x86-pthread-gasnet/ocrrun
@@ -50,10 +50,58 @@ fi
 RES=`grep "GASNet" ${OCR_CONFIG}`
 
 if [[ "$RES" != "" ]]; then
-    #Default to 2 nodes for now
+
+    if [[ "${GASNET_CONDUIT}" == "" ]]; then
+        echo "error: The GASNET_CONDUIT env variable is not defined"
+        exit 1
+    fi
+
+    if [[ "${OCR_NODEFILE}" != "" ]]; then
+        # count words since hostnames shouldn't have spaces (-l only counts new lines)
+        NODECOUNT=`more ${OCR_NODEFILE} | wc -w`
+        if [[ "${OCR_NUM_NODES}" != "${NODECOUNT}" ]]; then
+            OLD_VALUE=${OCR_NUM_NODES}
+            OCR_NUM_NODES=${NODECOUNT}
+            if [[ "${OLD_VALUE}" != "" ]]; then
+                echo "Warning: OCR_NUM_NODES differs from number of nodes declared in OCR_NODEFILE (${OLD_VALUE} and ${NODECOUNT})"
+            fi
+        fi
+
+        if [[ "${GASNET_CONDUIT}" == "ibv" ]]; then
+            if [[ "${GASNET_IBV_SPAWNER}" == "ssh" ]]; then
+                export GASNET_SSH_NODEFILE=${OCR_NODEFILE}
+            else
+                echo "Warning: ocrrun assumes IBV/MPI spawn uses intel mpi"
+                export MPIRUN_CMD="mpirun -np %N -machinefile ${OCR_NODEFILE} %C"
+            fi
+        else
+            echo "error: ocrrun does not know how to use OCR_NODEFILE when conduit=${GASNET_CONDUIT}"
+            exit 1
+        fi
+    fi
+
+    # Try to guess the gasnet launcher
+    if [[ "${GASNET_LAUNCHER}" == "" ]]; then
+        if [[ "${GASNET_CONDUIT}" == "ibv" ]]; then
+            GASNET_LAUNCHER=gasnetrun_ibv
+        elif [[ "${GASNET_CONDUIT}" == "udp" ]]; then
+            GASNET_LAUNCHER=amudprun
+        elif [[ "${GASNET_CONDUIT}" == "mpi" ]]; then
+            GASNET_LAUNCHER=gasnetrun_mpi
+        else
+            echo "error: GASNET_LAUNCHER is not unknown for conduit=${GASNET_CONDUIT}"
+            exit 1
+        fi
+    fi
+
+    #If nothing has provided default to 2 instances on local node
     #TODO This information should be extracted from the config file
-    NB_NODES=2
-    gasnetrun_${GASNET_CONDUIT} -n ${NB_NODES} ${PROGRAM_BIN} -ocr:cfg ${OCR_CONFIG}
+    if [[ "${OCR_NUM_NODES}" == "" ]]; then
+        OCR_NUM_NODES=2
+    fi
+
+    ${GASNET_LAUNCHER} -n ${OCR_NUM_NODES} ${PROGRAM_BIN} -ocr:cfg ${OCR_CONFIG}
+
     RET_CODE=$?
     exit ${RET_CODE}
 fi
