OCR: Multiple patches improving stability of distributed OCR
[See task #93]

 - Implement helper-mode to avoid deadlocks
 - Fix auto-placement mix up. Now alter destLocation and keep affinity in msg
 - Fix unresolved templates when auto-distributing
 - Add bin/ folder to host ocrrun
 - Add experimental hybrid comm/comp worker (HYBRID_COMM_COMP_WORKER)
 - Add ocrAffinityGetCurrent to allow for spawning EDTs in current
   EDT's affinity group
 - Add limitation assertion for distributed finish EDT (allows fully local ones)
 - Changed DB concurrent fetch implementation causing potential deadlock
   in helper mode
 - Fix DB_FREE message support
 - Add support for dependence mode to be available all the way down to
   EDT execution
 - Turned affinities into real GUIDs. Add support for affinity
   metadata cloning
 - Various cleanup

Change-Id: Iced2a3683f87fe081adfc3973ebfb8a821a88c3c

diff --git a/ocr/tests/ocrTests b/ocr/tests/ocrTests
--- a/ocr/tests/ocrTests
+++ b/ocr/tests/ocrTests
@@ -83,7 +83,8 @@ fi
 if [ -n "${OCR_LIBRARY_ITF}" ]; then
     CFLAGS="$CFLAGS -DOCR_LIBRARY_ITF=1"
 fi
-export LDFLAGS="-L${OCR_INSTALL}/lib -locr -lpthread"
+
+export LDFLAGS="-L${OCR_INSTALL}/lib -locr -lpthread ${OCR_LDFLAGS}"
 export OCR_TESTS_BIN_OUTPUT=
 
 if [ -z "${OCR_CONFIG}" ]; then
@@ -100,9 +101,11 @@ export OCR_FLAGS=" -ocr:cfg ${OCR_CONFIG}"
 BIN_DIR=${OCR_INSTALL}/bin
 LIB_DIR=${OCR_INSTALL}/lib
 
-if [ ! -x ${LIB_DIR}/libocr.so ]; then
-        echo "ERROR ocr lib not found in the ${OCR_INSTALL}/lib"
-        exit 1
+if [ -x ${LIB_DIR}/libocr.so -o -e ${LIB_DIR}/libocr.a ]; then
+    echo "OCR library found in ${OCR_INSTALL}/lib"
+else
+    echo "ERROR OCR library not found in ${OCR_INSTALL}/lib"
+    exit 1
 fi
 
 export PATH=${BIN_DIR}:${PATH}
